`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 2026/06/30 19:54:40
// Design Name: 
// Module Name: cpu_assertions
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


`timescale 1ns / 1ps

module cpu_assertions (
    input logic        clk,
    input logic        rst,

    input logic        id_valid,
    input logic        ex_valid,
    input logic        mem_valid,
    input logic        wb_valid,

    input logic        stall,
    input logic        redirect_valid,

    input logic        commit_valid,
    input logic        commit_rd_we,
    input logic [4:0]  commit_rd,
    input logic        commit_mem_we,

    input logic [31:0] x0_value,
    
    input logic        wb_regwrite,
    input logic [4:0]  wb_rd,
    input logic [31:0] wb_wdata,
    
    input logic [4:0]  id_rs1,
    input logic [4:0]  id_rs2,
    input logic [31:0] id_rs1_val,
    input logic [31:0] id_rs2_val
);

    // 1. x0 永远为 0
    property p_x0_is_zero;
        @(negedge clk) disable iff (rst)
            x0_value == 32'd0;
    endproperty

    assert property (p_x0_is_zero)
        else $error("[SVA] x0 changed from zero");

    // 2. 任何架构寄存器写回都不能写 x0
    property p_no_arch_write_x0;
        @(negedge clk) disable iff (rst)
            commit_rd_we |-> (commit_rd != 5'd0);
    endproperty

    assert property (p_no_arch_write_x0)
        else $error("[SVA] commit writes x0");

    // 3. Store 必须是有效退休指令的一部分
    property p_store_requires_commit;
        @(negedge clk) disable iff (rst)
            commit_mem_we |-> commit_valid;
    endproperty

    assert property (p_store_requires_commit)
        else $error("[SVA] store side effect without valid commit");

    // 4. redirect 只能由 EX 中的真实指令触发
    property p_redirect_requires_ex_valid;
        @(negedge clk) disable iff (rst)
            redirect_valid |-> ex_valid;
    endproperty

    assert property (p_redirect_requires_ex_valid)
        else $error("[SVA] redirect generated by invalid EX stage");

    // 5. load-use stall 时，ID 指令保持、EX 注入 bubble
    property p_stall_inserts_ex_bubble;
        @(negedge clk) disable iff (rst)
            stall |=> (!ex_valid);
    endproperty

    assert property (p_stall_inserts_ex_bubble)
        else $error("[SVA] stall did not inject EX bubble");
        
    // WB 与 ID 同周期访问同一寄存器时，
    // ID 读口必须直接看到 WB 正在写回的数据。
    property p_wb_to_id_bypass_rs1;
        @(negedge clk) disable iff (rst)
            (wb_regwrite &&
             (wb_rd != 5'd0) &&
             (wb_rd == id_rs1))
            |-> (id_rs1_val == wb_wdata);
    endproperty
    
    assert property (p_wb_to_id_bypass_rs1)
        else $error("[SVA] WB-to-ID bypass failed on rs1");
    
    
    property p_wb_to_id_bypass_rs2;
        @(negedge clk) disable iff (rst)
            (wb_regwrite &&
             (wb_rd != 5'd0) &&
             (wb_rd == id_rs2))
            |-> (id_rs2_val == wb_wdata);
    endproperty
    
    assert property (p_wb_to_id_bypass_rs2)
        else $error("[SVA] WB-to-ID bypass failed on rs2");

endmodule
